#version 460
#extension GL_GOOGLE_include_directive: require

#include "utils/pbr.glsl"
#include "include/shaders/types.h"

layout (local_size_x = 16, local_size_y = 16) in;

#ifdef UNPACK_MAIN
layout (set = 0, binding = 0) uniform sampler2D i_equirect;
layout (set = 0, binding = 1) writeonly uniform image2DArray o_cubemap;
#endif

#ifdef CONVOLUTE_MAIN
layout (set = 0, binding = 0) uniform samplerCube i_cubemap;
layout (set = 0, binding = 1) writeonly uniform image2DArray o_convolution;
#endif

const vec3 kFaceForward[6] = vec3[](
    vec3( 1,  0,  0),
    vec3(-1,  0,  0),
    vec3( 0,  1,  0),
    vec3( 0, -1,  0),
    vec3( 0,  0,  1),
    vec3( 0,  0, -1)
);

const vec3 kFaceRight[6] = vec3[](
    vec3( 0,  0, -1),
    vec3( 0,  0,  1),
    vec3( 1,  0,  0),
    vec3( 1,  0,  0),
    vec3( 1,  0,  0),
    vec3(-1,  0,  0)
);

const vec3 kFaceUp[6] = vec3[](
    vec3( 0, -1,  0),
    vec3( 0, -1,  0),
    vec3( 0,  0,  1),
    vec3( 0,  0, -1),
    vec3( 0, -1,  0),
    vec3( 0, -1,  0)
);

vec2 to_ndc(vec2 px, vec2 size)
{
    return ((px + vec2(0.5F)) / size) * 2.0F - 1.0F;
}

vec2 to_equirect(vec3 dir)
{
    return vec2(
        atan(dir.z, dir.x) * (0.5F / kPI) + 0.5F,
        acos(clamp(dir.y, -1.0F, 1.0F)) / kPI
    );
}

#ifdef UNPACK_MAIN
void main()
{
    ivec3 image_size = imageSize(o_cubemap);
    if (any(greaterThanEqual(gl_GlobalInvocationID.xy, uvec2(image_size.xy))))
        return;

    uint face = gl_GlobalInvocationID.z;

    vec2 pixel = vec2(gl_GlobalInvocationID.xy);
    vec2 uv = to_ndc(pixel, vec2(image_size.xy));

    vec3 dir = normalize(kFaceForward[face] + uv.x * kFaceRight[face] + uv.y * kFaceUp[face]);
    vec4 color = textureLod(i_equirect, to_equirect(dir), 0.0F);

    imageStore(o_cubemap, ivec3(gl_GlobalInvocationID.xyz), color);
}
#endif

#ifdef CONVOLUTE_MAIN
void main()
{
    ivec3 image_size = imageSize(o_convolution);
    if (any(greaterThanEqual(gl_GlobalInvocationID.xy, uvec2(image_size.xy))))
        return;

    uint face = gl_GlobalInvocationID.z;

    vec2 pixel = vec2(gl_GlobalInvocationID.xy);
    vec2 uv = to_ndc(pixel, vec2(image_size.xy));

    vec3 dir   = normalize(kFaceForward[face] + uv.x * kFaceRight[face] + uv.y * kFaceUp[face]);
    vec3 right = normalize(kFaceRight[face] - dir * dot(dir, kFaceRight[face]));
    vec3 up    = cross(dir, right);
    vec3 irradiance = vec3(0.0);

    float sampleDelta = 0.005;
    float nrSamples = 0.0;
    for(float phi = 0.0; phi < 2.0 * kPI; phi += sampleDelta)
    {
        for(float theta = 0.0; theta < 0.5 * kPI; theta += sampleDelta)
        {
            // spherical to cartesian (in tangent space)
            vec3 tangentSample = vec3(sin(theta) * cos(phi),  sin(theta) * sin(phi), cos(theta));
            // tangent space to world
            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * dir;

            irradiance += textureLod(i_cubemap, sampleVec, 0.0F).rgb * cos(theta) * sin(theta);
            nrSamples++;
        }
    }

    irradiance = kPI * irradiance * (1.0 / float(nrSamples));
    imageStore(o_convolution, ivec3(gl_GlobalInvocationID.xyz), vec4(irradiance, 1.0));
}
#endif
