#version 460

#extension GL_GOOGLE_include_directive: require

#include "utils/math.glsl"
#include "utils/gather.glsl"
#include "include/shaders/types.h"

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer MeshesData
{
    MeshData meshes_data[];
};

layout (scalar, binding = 1) readonly buffer MeshInstances
{
    MeshInstance mesh_instances[];
};

layout (binding = 2) buffer MeshesDrawCommandsCount
{
    uint draw_commands_count;
};

#ifdef FOR_LATE_OCCLUSION_TEST
layout (binding = 3) buffer MeshVisibilityBuffer
#else
layout (binding = 3) readonly buffer MeshVisibilityBuffer
#endif
{
    uint mesh_visibility_buffer[];
};

layout (binding = 4) readonly buffer FrameCullDataBuffer
{
    FrameCullData frame_cull;
};

#ifdef FOR_MESH_PIPELINE
layout (binding = 5) writeonly buffer DrawMeshletsIndirects
{
    DrawTaskCommandIndirect draw_indirect_cmds[];
};
#else
layout (binding = 5) writeonly buffer DrawIndexedIndirects
{
    DrawIndexedIndirect draw_indirect_cmds[];
};
#endif

#ifdef FOR_LATE_OCCLUSION_TEST
layout (binding = 6) uniform sampler2D depth_pyramid;
#endif

void main()
{
    uint mi = gl_WorkGroupID.x;
    uint ti = gl_LocalInvocationID.x;

    uint idx = mi * gl_WorkGroupSize.x + ti;
    bool inv_visibility_bit = (GET_BIT(mesh_visibility_buffer[idx >> 5], idx & 31u) == 0);

#ifdef FOR_LATE_OCCLUSION_TEST
    const bool early_out = GET_BIT(frame_cull.flags, kOcclusionCullBit) == 0;
#else
    bool early_out = inv_visibility_bit && GET_BIT(frame_cull.flags, kOcclusionCullBit) == 1;
#endif

    if (idx >= frame_cull.draw_count || early_out)
    {
        return;
    }

    // draw only last frame occluders
    uint mesh_idx = mesh_instances[idx].mesh_data_index;
    vec3 center = transform_vec3(vec3(meshes_data[mesh_idx].center[0], meshes_data[mesh_idx].center[1], meshes_data[mesh_idx].center[2]), mesh_instances[idx].pos_and_scale, mesh_instances[idx].rotation_quat);
    center = vec3(frame_cull.view * vec4(center, 1.0F));

    float scale = mesh_instances[idx].pos_and_scale.w;
    float radius = meshes_data[mesh_idx].radius * scale;

    bool visible = true;
    visible = visible && center.z * frame_cull.frustum[1] - abs(center.x) * frame_cull.frustum[0] > -radius;
    visible = visible && center.z * frame_cull.frustum[3] - abs(center.y) * frame_cull.frustum[2] > -radius;
    visible = visible && center.z - radius < -frame_cull.frustum[4] && center.z + radius > -frame_cull.frustum[5];
    visible = visible || GET_BIT(frame_cull.flags, kFrustumCullBit) == 0;

#ifdef FOR_LATE_OCCLUSION_TEST
    vec4 p_aabb;
    if (visible && GET_BIT(frame_cull.flags, kOcclusionCullBit) == 1 && project_sphere(center, radius, frame_cull.frustum[4], frame_cull.p00, frame_cull.p11, p_aabb))
    {
        vec2 pmd_size = vec2(p_aabb.z - p_aabb.x, p_aabb.w - p_aabb.y) * frame_cull.pyramid_size;
        float level = ceil(log2(max(pmd_size.x, pmd_size.y)));

#ifndef PLATFORM_MVK
        float pmd_depth = textureLod(depth_pyramid, (p_aabb.xy + p_aabb.zw) * 0.5, level).x;
#else
        float pmd_depth = textureGatherLodMin(depth_pyramid, (p_aabb.xy + p_aabb.zw) * 0.5, level, 0);
#endif
        float spr_depth = -frame_cull.frustum[4] / (center.z + radius);

        visible = visible && spr_depth >= pmd_depth;
    }
#endif

#ifdef FOR_LATE_OCCLUSION_TEST
    const bool skip_draw = false;
#else
    const bool skip_draw = false;
#endif

    if (visible && !skip_draw)
    {
        uint lod_base = 0;
        float dist = max(length(center) - radius, 0);

        for (uint i = 1; i < meshes_data[mesh_idx].lod_count; ++i)
        {
            if ((meshes_data[mesh_idx].lod_array[i].error * scale / dist) <= frame_cull.lod_threshold)
                lod_base = i;
            else
                break;
        }

        lod_base = GET_BIT(frame_cull.flags, kLodFlagBit) == 0 ? 0 : lod_base;
        MeshLod selected_lod = meshes_data[mesh_idx].lod_array[lod_base];

#ifdef FOR_MESH_PIPELINE
        uint taskCount = (selected_lod.meshlets_count + kTaskWorkGroups - 1) / kTaskWorkGroups;
        uint dci = atomicAdd(draw_commands_count, taskCount);
        for (uint i = taskCount; i > 0; i--)
        {
            uint dcii = dci + taskCount - i;
            uint offset = kTaskWorkGroups * (taskCount - i);
            draw_indirect_cmds[dcii].instance_id = idx;
            draw_indirect_cmds[dcii].meshlet_offset = selected_lod.base_meshlet + offset;
            draw_indirect_cmds[dcii].visibility_offset = mesh_instances[idx].visibility_offset + offset;
#ifdef FOR_LATE_OCCLUSION_TEST
            uint drawn_in_early_bit = !inv_visibility_bit ? 1 : 0;
            draw_indirect_cmds[dcii].meshlet_count = min(selected_lod.meshlets_count - offset, kTaskWorkGroups) | drawn_in_early_bit << 31;
#else
            draw_indirect_cmds[dcii].meshlet_count = min(selected_lod.meshlets_count - offset, kTaskWorkGroups);
#endif
        }
#else
        uint dci = atomicAdd(draw_commands_count, 1);
        draw_indirect_cmds[dci].instance_count = 1;
#ifndef PLATFORM_MVK
        draw_indirect_cmds[dci].first_instance = 0;
#else
        draw_indirect_cmds[dci].first_instance = dci;
#endif
        draw_indirect_cmds[dci].vertex_offset = int(meshes_data[mesh_idx].base_vertex);

        draw_indirect_cmds[dci].instance_id = idx;
        draw_indirect_cmds[dci].first_index = selected_lod.base_index;
        draw_indirect_cmds[dci].index_count = selected_lod.indices_count;
#endif
    }

#ifdef FOR_LATE_OCCLUSION_TEST
    if (visible)
        atomicOr(mesh_visibility_buffer[idx >> 5], 1u << (idx & 31u));
    else
        atomicAnd(mesh_visibility_buffer[idx >> 5], ~(1u << (idx & 31u)));
#endif
}
