#version 460

#extension GL_GOOGLE_include_directive: require

#include "utils/math.glsl"
#include "utils/gather.glsl"
#include "include/shaders/types.h"

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout (binding = 0) uniform sampler2D input_depth;
layout (binding = 1, r32f) uniform writeonly image2D output_depth;

layout (push_constant) uniform block
{
    vec2 output_image_size;
};

void main()
{
    uvec2 pos = gl_GlobalInvocationID.xy;
#ifndef PLATFORM_MVK
    float result = texture(input_depth, (vec2(pos) + vec2(0.5)) / output_image_size).r;
#else
    float result = textureGatherMin(input_depth, (vec2(pos) + vec2(0.5)) / output_image_size, 0);
#endif
    imageStore(output_depth, ivec2(pos), vec4(result));
}
