#version 460

#extension GL_GOOGLE_include_directive: require

#include "utils/math.glsl"
#include "utils/gather.glsl"
#include "include/shaders/types.h"

layout (local_size_x = kTaskWorkGroups, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0, set = 0) readonly buffer Meshlets        { Meshlet meshlets[]; };
layout (binding = 1, set = 0) readonly buffer MeshletVertices { uint meshlets_vertices[]; };
layout (binding = 1, set = 0) readonly buffer MeshletIndices  { uint8_t meshlets_indices[]; };
layout (binding = 2, set = 0) readonly buffer MeshesData      { MeshData meshes_data[]; };
layout (binding = 3, scalar)  readonly buffer MeshInstances   { MeshInstance mesh_instances[]; };

layout (binding = 4, set = 0) readonly buffer DrawMeshletsIndirects { DrawTaskCommandIndirect draw_mesh_cmds[]; };
layout (binding = 5, set = 0) readonly buffer FrameCullDataBuffer   { FrameCullData frame_cull; };

layout (binding = 6, set = 0) writeonly buffer Indices              { uint indices[]; };
layout (binding = 7, set = 0) writeonly buffer DrawindexedIndirects { DrawIndexedIndirect draw_indirects[]; };
layout (binding = 8, set = 0) buffer IndexedDrawCounts              { uint indexed_draw_counts[2]; };

#ifdef FOR_LATE_OCCLUSION_TEST
layout (binding = 9)  buffer MeshletsVisibilityBuffer { uint meshlets_visibility_buffer[]; };
layout (binding = 10) uniform sampler2D depth_pyramid;
#else
layout (binding = 9) readonly buffer MeshletsVisibilityBuffer { uint meshlets_visibility_buffer[]; };
#endif

shared uint s_indices_count;
shared uint s_indices_offset_global;

layout (scalar, push_constant) uniform PushConstants
{
    uint offset;
} pc;

void main()
{
    uint instance_id      = draw_mesh_cmds[gl_WorkGroupID.x + pc.offset].instance_id;
    uint meshlets_in_task = draw_mesh_cmds[gl_WorkGroupID.x + pc.offset].meshlet_count & 0x7FFFFFFFu;
    uint meshlet_id       = draw_mesh_cmds[gl_WorkGroupID.x + pc.offset].meshlet_offset + gl_LocalInvocationID.x;
    uint visibility_bit   = draw_mesh_cmds[gl_WorkGroupID.x + pc.offset].visibility_offset + gl_LocalInvocationID.x;
    uint cmd_base_vertex = meshes_data[mesh_instances[instance_id].mesh_data_index].base_vertex;

    if (gl_LocalInvocationID.x == 0)
    {
        s_indices_count = 0;
        s_indices_offset_global = 0;
    }
    barrier();

    vec3 sphere_center = vec3(
        meshlets[meshlet_id].sphere_center[0],
        meshlets[meshlet_id].sphere_center[1],
        meshlets[meshlet_id].sphere_center[2]
    );

    float sphere_radius = float(meshlets[meshlet_id].sphere_radius) * mesh_instances[instance_id].pos_and_scale.w;
    vec3 view_center = (frame_cull.view * vec4(transform_vec3(sphere_center, mesh_instances[instance_id].pos_and_scale, mesh_instances[instance_id].rotation_quat), 1.0F)).xyz;

    bool visible = true;

#ifdef ENABLE_CONE_CULL
    if (DBG_GET_BIT1(frame_cull.flags, kMeshletConeCullBit) == 1)
    {
        vec3 cull_cone_axis = vec3(
            meshlets[meshlet_id].cone_axis[0],
            meshlets[meshlet_id].cone_axis[1],
            meshlets[meshlet_id].cone_axis[2]
        );

        vec3 view_axis = (frame_cull.view * vec4(quat_rotate_vec3(cull_cone_axis, mesh_instances[instance_id].rotation_quat), 0.0F)).xyz;
        visible = dot(view_center, view_axis) < float(meshlets[meshlet_id].cone_cutoff) * length(view_center) + sphere_radius;
    }
#endif

    if (DBG_GET_BIT1(frame_cull.flags, kMeshletFrustumCullBit) == 1)
    {
        visible = visible && view_center.z * frame_cull.frustum[1] - abs(view_center.x) * frame_cull.frustum[0] > -sphere_radius;
        visible = visible && view_center.z * frame_cull.frustum[3] - abs(view_center.y) * frame_cull.frustum[2] > -sphere_radius;
        visible = visible && view_center.z - sphere_radius < -frame_cull.frustum[4] && view_center.z + sphere_radius > -frame_cull.frustum[5];
    }

    vec4 p_aabb;
    if (visible && DBG_GET_BIT1(frame_cull.flags, kSmallMeshletsCullBit) == 1 && project_sphere(view_center, sphere_radius, frame_cull.frustum[4], frame_cull.p00, frame_cull.p11, p_aabb))
    {
        vec2 pmin = p_aabb.xy * frame_cull.viewport_size;
        vec2 pmax = p_aabb.zw * frame_cull.viewport_size;

        // TODO: I think this should be 1/(2^subPixPrecBits) or smth like that
        const float sp_prec = 1.0 / 256.0;
        visible = visible && !(round(pmin.x - sp_prec) == round(pmax.x) || round(pmin.y) == round(pmax.y + sp_prec));
    }

    bool was_visible_last_frame = GET_BIT(meshlets_visibility_buffer[visibility_bit >> 5], visibility_bit & 31) == 1;
    bool emit = visible && gl_LocalInvocationID.x < meshlets_in_task;

#ifdef FOR_LATE_OCCLUSION_TEST
    bool drawn_in_early = was_visible_last_frame && visible && GET_BIT(draw_mesh_cmds[gl_WorkGroupID.x].meshlet_count, 31) == 1;
    if (visible && DBG_GET_BIT1(frame_cull.flags, kMeshletOcclusionCullBit) == 1 && project_sphere(view_center, sphere_radius, frame_cull.frustum[4], frame_cull.p00, frame_cull.p11, p_aabb))
    {
        vec2 pmd_size = vec2(p_aabb.z - p_aabb.x, p_aabb.w - p_aabb.y) * frame_cull.pyramid_size;
        float level = ceil(log2(max(pmd_size.x, pmd_size.y)));
        float spr_depth = -frame_cull.frustum[4] / (view_center.z + sphere_radius);

#ifndef PLATFORM_MVK
        float pmd_depth = textureLod(depth_pyramid, (p_aabb.xy + p_aabb.zw) * 0.5, level).x;
#else
        float pmd_depth = textureGatherLodMin(depth_pyramid, (p_aabb.xy + p_aabb.zw) * 0.5, level, 0);
#endif

        visible = visible && spr_depth >= pmd_depth;
    }

    if (gl_LocalInvocationID.x < meshlets_in_task)
    {
        if (visible)
            atomicOr(meshlets_visibility_buffer[visibility_bit >> 5], 1u << (visibility_bit & 31));
        else
            atomicAnd(meshlets_visibility_buffer[visibility_bit >> 5], ~(1u << (visibility_bit & 31)));
    }

    emit = emit && visible && (!drawn_in_early || DBG_GET_BIT1(frame_cull.flags, kMeshletOcclusionCullBit) == 0);
#else
    emit = emit && (was_visible_last_frame || DBG_GET_BIT1(frame_cull.flags, kMeshletOcclusionCullBit) == 0);
#endif

    uint indices_offset_local = emit ? atomicAdd(s_indices_count, uint(meshlets[meshlet_id].triangles_count) * 3) : 0;

    barrier();
    if (gl_LocalInvocationID.x == 0)
    {
        s_indices_offset_global = atomicAdd(indexed_draw_counts[0], s_indices_count);
        uint dci = atomicAdd(indexed_draw_counts[1], 1);

#ifndef PLATFORM_MVK
        draw_indirects[dci].first_instance = 0;
#else
        draw_indirects[dci].first_instance = dci;
#endif
        draw_indirects[dci].instance_count = 1;
        draw_indirects[dci].instance_id = instance_id;
        draw_indirects[dci].vertex_offset = int(cmd_base_vertex);

        draw_indirects[dci].index_count = s_indices_count;
        draw_indirects[dci].first_index = s_indices_offset_global;
    }

    barrier();
    if (emit)
    {
        indices_offset_local += s_indices_offset_global;

        const uint base_vertex = meshlets[meshlet_id].data_offset / 4;
        const uint base_index  = meshlets[meshlet_id].data_offset + uint(meshlets[meshlet_id].vertices_count) * 4;

        for (uint i = 0; i < int(meshlets[meshlet_id].triangles_count); ++i)
        {
            const uint store_base = indices_offset_local + i * 3;
            const uint iid = base_index + i * 3;

            indices[store_base + 0] = meshlets_vertices[base_vertex + uint(meshlets_indices[iid + 0])];
            indices[store_base + 1] = meshlets_vertices[base_vertex + uint(meshlets_indices[iid + 1])];
            indices[store_base + 2] = meshlets_vertices[base_vertex + uint(meshlets_indices[iid + 2])];
        }
    }
}
